runtime: nodejs18  # Sesuaikan versi Node.js yang Anda gunakan

env_variables:
  DB_USERNAME: "root"          # Sesuaikan dengan nama user database MySQL di GCP
  DB_PASSWORD: "your-password" # Sesuaikan dengan password database
  DB_NAME: "crud_mahasiswa"    # Nama database
  DB_HOST: "your-db-host"      # Alamat host database (misalnya IP atau Cloud SQL instance connection name)

handlers:
  - url: /
    static_files: public
    upload: public

  - url: /
    script: auto
