runtime: nodejs18
instance_class: F2

env_variables:
  NODE_ENV: 'production'

# Definisi handler
handlers:
  # Jika Anda memiliki file statis (misalnya CSS, JS, gambar), pastikan ada folder 'public'
  - url: /public
    static_dir: public

  # Tangkap semua URL dan arahkan ke aplikasi Node.js
  - url: /.*
    script: auto

# runtime: nodejs18
# instance_class: F2

# env_variables:
#   NODE_ENV: 'production'
#   DB_HOST: '/cloudsql/YOUR_INSTANCE_CONNECTION_NAME'
#   DB_USER: 'root'
#   DB_PASS: 'YOUR_DB_PASSWORD'
#   DB_NAME: 'crud_mahasiswa'

# beta_settings:
#   cloud_sql_instances: YOUR_INSTANCE_CONNECTION_NAME

# handlers:
#   - url: /public
#     static_dir: public

#   - url: /.*
#     script: auto
