runtime: nodejs18
instance_class: F2

env_variables:
  NODE_ENV: 'production'

handlers:
  - url: /
    static_files: public/index.html
    upload: public/index.html
  - url: /public
    static_dir: public

  - url: /.*
    script: auto
